apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat-app
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
        - name: tomcat-container
          image: chay972/tomcat:latest
          ports: 
            - containerPort: 8080
